version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker_network
    restart: always
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    depends_on: 
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - docker_network
    restart: always
  wordpress:
    container_name: wordpress
    build: ./wordpress
    image: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - docker_network
    restart: always
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/sutku/data/mysql
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/sutku/data/wordpress
      o: bind
networks:
  docker_network: