version: "2"

services:
  mariadb:
    build: ./mariadb
    image: mariadb
    env_file:
      - mariadb/.maria_env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker_network
    restart: always
  nginx:
    build: ./nginx
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    depends_on: 
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - docker_network
    restart: always
  wordpress:
    build: ./wordpress
    image: wordpress
    env_file:
      - .env
    depends_on: 
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - docker_network
    restart: always

volumes:
  mariadb:
  wordpress:

networks:
  docker_network: